/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prestamo;

/**
 *
 * @author user
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        prestcash = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_inicio = new javax.swing.JButton();
        btn_pagos = new javax.swing.JButton();
        inicio2 = new javax.swing.JButton();
        btn_historial = new javax.swing.JButton();
        btn_solicitarPrestamo = new javax.swing.JButton();
        inicio5 = new javax.swing.JButton();
        inicio6 = new javax.swing.JButton();
        inicio7 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        indicador = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        Contenido2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setName(""); // NOI18N
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        prestcash.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        prestcash.setForeground(new java.awt.Color(255, 255, 255));
        prestcash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prestcash.setText("PRESTCASH");

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        btn_inicio.setBackground(new java.awt.Color(102, 102, 102));
        btn_inicio.setForeground(new java.awt.Color(255, 255, 255));
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(null);
        btn_inicio.setBorderPainted(false);
        btn_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_pagos.setBackground(new java.awt.Color(102, 102, 102));
        btn_pagos.setForeground(new java.awt.Color(255, 255, 255));
        btn_pagos.setText("Pagos");
        btn_pagos.setBorder(null);
        btn_pagos.setBorderPainted(false);
        btn_pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagosActionPerformed(evt);
            }
        });

        inicio2.setBackground(new java.awt.Color(102, 102, 102));
        inicio2.setForeground(new java.awt.Color(255, 255, 255));
        inicio2.setText("Vacio");
        inicio2.setBorder(null);
        inicio2.setBorderPainted(false);
        inicio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio2ActionPerformed(evt);
            }
        });

        btn_historial.setBackground(new java.awt.Color(102, 102, 102));
        btn_historial.setForeground(new java.awt.Color(255, 255, 255));
        btn_historial.setText("Historial");
        btn_historial.setBorder(null);
        btn_historial.setBorderPainted(false);
        btn_historial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historialActionPerformed(evt);
            }
        });

        btn_solicitarPrestamo.setBackground(new java.awt.Color(102, 102, 102));
        btn_solicitarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btn_solicitarPrestamo.setText("Solicitar Préstamo");
        btn_solicitarPrestamo.setBorder(null);
        btn_solicitarPrestamo.setBorderPainted(false);
        btn_solicitarPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_solicitarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarPrestamoActionPerformed(evt);
            }
        });

        inicio5.setBackground(new java.awt.Color(102, 102, 102));
        inicio5.setForeground(new java.awt.Color(255, 255, 255));
        inicio5.setText("Vacio");
        inicio5.setBorder(null);
        inicio5.setBorderPainted(false);
        inicio5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio5ActionPerformed(evt);
            }
        });

        inicio6.setBackground(new java.awt.Color(102, 102, 102));
        inicio6.setForeground(new java.awt.Color(255, 255, 255));
        inicio6.setText("Vacio");
        inicio6.setBorder(null);
        inicio6.setBorderPainted(false);
        inicio6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio6ActionPerformed(evt);
            }
        });

        inicio7.setBackground(new java.awt.Color(102, 102, 102));
        inicio7.setForeground(new java.awt.Color(255, 255, 255));
        inicio7.setText("Vacio");
        inicio7.setBorder(null);
        inicio7.setBorderPainted(false);
        inicio7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prestcash, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inicio6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(inicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(inicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(inicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_solicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(prestcash, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(inicio6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(inicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(inicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btn_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(inicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_solicitarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        header.setBackground(new java.awt.Color(0, 204, 204));

        bienvenido.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        bienvenido.setText("Bienvenidos a Prestcash");

        indicador.setText("Administrador/Gestor de Prestamos");

        fecha.setText("jLabel2");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1441, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indicador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        mensaje.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        mensaje.setText("Tu Prestamo, Nuestra Prioridad");

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        Contenido2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Contenido2Layout = new javax.swing.GroupLayout(Contenido2);
        Contenido2.setLayout(Contenido2Layout);
        Contenido2Layout.setHorizontalGroup(
            Contenido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1846, Short.MAX_VALUE)
        );
        Contenido2Layout.setVerticalGroup(
            Contenido2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Contenido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pagosActionPerformed

    private void inicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio2ActionPerformed

    private void btn_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_historialActionPerformed

    private void btn_solicitarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solicitarPrestamoActionPerformed

    private void inicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio5ActionPerformed

    private void inicio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio6ActionPerformed

    private void inicio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido2;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btn_historial;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_pagos;
    private javax.swing.JButton btn_solicitarPrestamo;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel indicador;
    private javax.swing.JButton inicio2;
    private javax.swing.JButton inicio5;
    private javax.swing.JButton inicio6;
    private javax.swing.JButton inicio7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel prestcash;
    // End of variables declaration//GEN-END:variables
}
